/*
$Revision$
Tableau Story global.js
Contents:
	= Modernizr 2.6.2
	= throttledresize
	= jQuery Waypoints 2.0.2
	= Javascript mouse wheel 3.0.6
	= jScrollPane - v2.0.0beta12
	= Respond.js v1.1.0
	= TAB Main Object
	= DOM Ready Event
*/


/* Modernizr 2.6.2 (Custom Build) | MIT & BSD
 * Build: http://modernizr.com/download/#-backgroundsize-testprop-testallprops-domprefixes
 */
;window.Modernizr=function(a,b,c){function w(a){i.cssText=a}function x(a,b){return w(prefixes.join(a+";")+(b||""))}function y(a,b){return typeof a===b}function z(a,b){return!!~(""+a).indexOf(b)}function A(a,b){for(var d in a){var e=a[d];if(!z(e,"-")&&i[e]!==c)return b=="pfx"?e:!0}return!1}function B(a,b,d){for(var e in a){var f=b[a[e]];if(f!==c)return d===!1?a[e]:y(f,"function")?f.bind(d||b):f}return!1}function C(a,b,c){var d=a.charAt(0).toUpperCase()+a.slice(1),e=(a+" "+m.join(d+" ")+d).split(" ");return y(b,"string")||y(b,"undefined")?A(e,b):(e=(a+" "+n.join(d+" ")+d).split(" "),B(e,b,c))}var d="2.6.2",e={},f=b.documentElement,g="modernizr",h=b.createElement(g),i=h.style,j,k={}.toString,l="Webkit Moz O ms",m=l.split(" "),n=l.toLowerCase().split(" "),o={},p={},q={},r=[],s=r.slice,t,u={}.hasOwnProperty,v;!y(u,"undefined")&&!y(u.call,"undefined")?v=function(a,b){return u.call(a,b)}:v=function(a,b){return b in a&&y(a.constructor.prototype[b],"undefined")},Function.prototype.bind||(Function.prototype.bind=function(b){var c=this;if(typeof c!="function")throw new TypeError;var d=s.call(arguments,1),e=function(){if(this instanceof e){var a=function(){};a.prototype=c.prototype;var f=new a,g=c.apply(f,d.concat(s.call(arguments)));return Object(g)===g?g:f}return c.apply(b,d.concat(s.call(arguments)))};return e}),o.backgroundsize=function(){return C("backgroundSize")};for(var D in o)v(o,D)&&(t=D.toLowerCase(),e[t]=o[D](),r.push((e[t]?"":"no-")+t));return e.addTest=function(a,b){if(typeof a=="object")for(var d in a)v(a,d)&&e.addTest(d,a[d]);else{a=a.toLowerCase();if(e[a]!==c)return e;b=typeof b=="function"?b():b,typeof enableClasses!="undefined"&&enableClasses&&(f.className+=" "+(b?"":"no-")+a),e[a]=b}return e},w(""),h=j=null,e._version=d,e._domPrefixes=n,e._cssomPrefixes=m,e.testProp=function(a){return A([a])},e.testAllProps=C,e}(this,this.document);


/*
* throttledresize: special jQuery event that happens at a reduced rate compared to "resize"
* https://github.com/louisremi/jquery-smartresize
* Copyright 2012 @louis_remi
* Licensed under the MIT license.
*/
(function(b){var f=b.event,c,g={_:0},a=0,d,e;c=f.special.throttledresize={setup:function(){b(this).on("resize",c.handler)},teardown:function(){b(this).off("resize",c.handler)},handler:function(h,j){var k=this,l=arguments;d=!0;e||(setInterval(function(){a++;if(a>c.threshold&&d||j)h.type="throttledresize",f.dispatch.apply(k,l),d=!1,a=0;9<a&&(b(g).stop(),e=!1,a=0)},30),e=!0)},threshold:0}})(jQuery);


// Generated by CoffeeScript 1.4.0
/*
jQuery Waypoints - v2.0.2
Copyright (c) 2011-2013 Caleb Troughton
Dual licensed under the MIT license and GPL license.
https://github.com/imakewebthings/jquery-waypoints/blob/master/licenses.txt
*/
(function(){var t=[].indexOf||function(t){for(var e=0,n=this.length;e<n;e++){if(e in this&&this[e]===t)return e}return-1},e=[].slice;(function(t,e){if(typeof define==="function"&&define.amd){return define("waypoints",["jquery"],function(n){return e(n,t)})}else{return e(t.jQuery,t)}})(this,function(n,r){var i,o,l,s,f,u,a,c,h,d,p,y,v,w,g,m;i=n(r);c=t.call(r,"ontouchstart")>=0;s={horizontal:{},vertical:{}};f=1;a={};u="waypoints-context-id";p="resize.waypoints";y="scroll.waypoints";v=1;w="waypoints-waypoint-ids";g="waypoint";m="waypoints";o=function(){function t(t){var e=this;this.$element=t;this.element=t[0];this.didResize=false;this.didScroll=false;this.id="context"+f++;this.oldScroll={x:t.scrollLeft(),y:t.scrollTop()};this.waypoints={horizontal:{},vertical:{}};t.data(u,this.id);a[this.id]=this;t.bind(y,function(){var t;if(!(e.didScroll||c)){e.didScroll=true;t=function(){e.doScroll();return e.didScroll=false};return r.setTimeout(t,n[m].settings.scrollThrottle)}});t.bind(p,function(){var t;if(!e.didResize){e.didResize=true;t=function(){n[m]("refresh");return e.didResize=false};return r.setTimeout(t,n[m].settings.resizeThrottle)}})}t.prototype.doScroll=function(){var t,e=this;t={horizontal:{newScroll:this.$element.scrollLeft(),oldScroll:this.oldScroll.x,forward:"right",backward:"left"},vertical:{newScroll:this.$element.scrollTop(),oldScroll:this.oldScroll.y,forward:"down",backward:"up"}};if(c&&(!t.vertical.oldScroll||!t.vertical.newScroll)){n[m]("refresh")}n.each(t,function(t,r){var i,o,l;l=[];o=r.newScroll>r.oldScroll;i=o?r.forward:r.backward;n.each(e.waypoints[t],function(t,e){var n,i;if(r.oldScroll<(n=e.offset)&&n<=r.newScroll){return l.push(e)}else if(r.newScroll<(i=e.offset)&&i<=r.oldScroll){return l.push(e)}});l.sort(function(t,e){return t.offset-e.offset});if(!o){l.reverse()}return n.each(l,function(t,e){if(e.options.continuous||t===l.length-1){return e.trigger([i])}})});return this.oldScroll={x:t.horizontal.newScroll,y:t.vertical.newScroll}};t.prototype.refresh=function(){var t,e,r,i=this;r=n.isWindow(this.element);e=this.$element.offset();this.doScroll();t={horizontal:{contextOffset:r?0:e.left,contextScroll:r?0:this.oldScroll.x,contextDimension:this.$element.width(),oldScroll:this.oldScroll.x,forward:"right",backward:"left",offsetProp:"left"},vertical:{contextOffset:r?0:e.top,contextScroll:r?0:this.oldScroll.y,contextDimension:r?n[m]("viewportHeight"):this.$element.height(),oldScroll:this.oldScroll.y,forward:"down",backward:"up",offsetProp:"top"}};return n.each(t,function(t,e){return n.each(i.waypoints[t],function(t,r){var i,o,l,s,f;i=r.options.offset;l=r.offset;o=n.isWindow(r.element)?0:r.$element.offset()[e.offsetProp];if(n.isFunction(i)){i=i.apply(r.element)}else if(typeof i==="string"){i=parseFloat(i);if(r.options.offset.indexOf("%")>-1){i=Math.ceil(e.contextDimension*i/100)}}r.offset=o-e.contextOffset+e.contextScroll-i;if(r.options.onlyOnScroll&&l!=null||!r.enabled){return}if(l!==null&&l<(s=e.oldScroll)&&s<=r.offset){return r.trigger([e.backward])}else if(l!==null&&l>(f=e.oldScroll)&&f>=r.offset){return r.trigger([e.forward])}else if(l===null&&e.oldScroll>=r.offset){return r.trigger([e.forward])}})})};t.prototype.checkEmpty=function(){if(n.isEmptyObject(this.waypoints.horizontal)&&n.isEmptyObject(this.waypoints.vertical)){this.$element.unbind([p,y].join(" "));return delete a[this.id]}};return t}();l=function(){function t(t,e,r){var i,o;r=n.extend({},n.fn[g].defaults,r);if(r.offset==="bottom-in-view"){r.offset=function(){var t;t=n[m]("viewportHeight");if(!n.isWindow(e.element)){t=e.$element.height()}return t-n(this).outerHeight()}}this.$element=t;this.element=t[0];this.axis=r.horizontal?"horizontal":"vertical";this.callback=r.handler;this.context=e;this.enabled=r.enabled;this.id="waypoints"+v++;this.offset=null;this.options=r;e.waypoints[this.axis][this.id]=this;s[this.axis][this.id]=this;i=(o=t.data(w))!=null?o:[];i.push(this.id);t.data(w,i)}t.prototype.trigger=function(t){if(!this.enabled){return}if(this.callback!=null){this.callback.apply(this.element,t)}if(this.options.triggerOnce){return this.destroy()}};t.prototype.disable=function(){return this.enabled=false};t.prototype.enable=function(){this.context.refresh();return this.enabled=true};t.prototype.destroy=function(){delete s[this.axis][this.id];delete this.context.waypoints[this.axis][this.id];return this.context.checkEmpty()};t.getWaypointsByElement=function(t){var e,r;r=n(t).data(w);if(!r){return[]}e=n.extend({},s.horizontal,s.vertical);return n.map(r,function(t){return e[t]})};return t}();d={init:function(t,e){var r;if(e==null){e={}}if((r=e.handler)==null){e.handler=t}this.each(function(){var t,r,i,s;t=n(this);i=(s=e.context)!=null?s:n.fn[g].defaults.context;if(!n.isWindow(i)){i=t.closest(i)}i=n(i);r=a[i.data(u)];if(!r){r=new o(i)}return new l(t,r,e)});n[m]("refresh");return this},disable:function(){return d._invoke(this,"disable")},enable:function(){return d._invoke(this,"enable")},destroy:function(){return d._invoke(this,"destroy")},prev:function(t,e){return d._traverse.call(this,t,e,function(t,e,n){if(e>0){return t.push(n[e-1])}})},next:function(t,e){return d._traverse.call(this,t,e,function(t,e,n){if(e<n.length-1){return t.push(n[e+1])}})},_traverse:function(t,e,i){var o,l;if(t==null){t="vertical"}if(e==null){e=r}l=h.aggregate(e);o=[];this.each(function(){var e;e=n.inArray(this,l[t]);return i(o,e,l[t])});return this.pushStack(o)},_invoke:function(t,e){t.each(function(){var t;t=l.getWaypointsByElement(this);return n.each(t,function(t,n){n[e]();return true})});return this}};n.fn[g]=function(){var t,r;r=arguments[0],t=2<=arguments.length?e.call(arguments,1):[];if(d[r]){return d[r].apply(this,t)}else if(n.isFunction(r)){return d.init.apply(this,arguments)}else if(n.isPlainObject(r)){return d.init.apply(this,[null,r])}else if(!r){return n.error("jQuery Waypoints needs a callback function or handler option.")}else{return n.error("The "+r+" method does not exist in jQuery Waypoints.")}};n.fn[g].defaults={context:r,continuous:true,enabled:true,horizontal:false,offset:0,triggerOnce:false};h={refresh:function(){return n.each(a,function(t,e){return e.refresh()})},viewportHeight:function(){var t;return(t=r.innerHeight)!=null?t:i.height()},aggregate:function(t){var e,r,i;e=s;if(t){e=(i=a[n(t).data(u)])!=null?i.waypoints:void 0}if(!e){return[]}r={horizontal:[],vertical:[]};n.each(r,function(t,i){n.each(e[t],function(t,e){return i.push(e)});i.sort(function(t,e){return t.offset-e.offset});r[t]=n.map(i,function(t){return t.element});return r[t]=n.unique(r[t])});return r},above:function(t){if(t==null){t=r}return h._filter(t,"vertical",function(t,e){return e.offset<=t.oldScroll.y})},below:function(t){if(t==null){t=r}return h._filter(t,"vertical",function(t,e){return e.offset>t.oldScroll.y})},left:function(t){if(t==null){t=r}return h._filter(t,"horizontal",function(t,e){return e.offset<=t.oldScroll.x})},right:function(t){if(t==null){t=r}return h._filter(t,"horizontal",function(t,e){return e.offset>t.oldScroll.x})},enable:function(){return h._invoke("enable")},disable:function(){return h._invoke("disable")},destroy:function(){return h._invoke("destroy")},extendFn:function(t,e){return d[t]=e},_invoke:function(t){var e;e=n.extend({},s.vertical,s.horizontal);return n.each(e,function(e,n){n[t]();return true})},_filter:function(t,e,r){var i,o;i=a[n(t).data(u)];if(!i){return[]}o=[];n.each(i.waypoints[e],function(t,e){if(r(i,e)){return o.push(e)}});o.sort(function(t,e){return t.offset-e.offset});return n.map(o,function(t){return t.element})}};n[m]=function(){var t,n;n=arguments[0],t=2<=arguments.length?e.call(arguments,1):[];if(h[n]){return h[n].apply(null,t)}else{return h.aggregate.call(null,n)}};n[m].settings={resizeThrottle:100,scrollThrottle:30};return i.load(function(){return n[m]("refresh")})})}).call(this);


/*! Copyright (c) 2011 Brandon Aaron (http://brandonaaron.net)
 * Licensed under the MIT License (LICENSE.txt).
 *
 * Thanks to: http://adomas.org/javascript-mouse-wheel/ for some pointers.
 * Thanks to: Mathias Bank(http://www.mathias-bank.de) for a scope bug fix.
 * Thanks to: Seamus Leahy for adding deltaX and deltaY
 *
 * Version: 3.0.6
 * 
 * Requires: 1.2.2+
 */
(function(a){function d(b){var c=b||window.event,d=[].slice.call(arguments,1),e=0,f=!0,g=0,h=0;return b=a.event.fix(c),b.type="mousewheel",c.wheelDelta&&(e=c.wheelDelta/120),c.detail&&(e=-c.detail/3),h=e,c.axis!==undefined&&c.axis===c.HORIZONTAL_AXIS&&(h=0,g=-1*e),c.wheelDeltaY!==undefined&&(h=c.wheelDeltaY/120),c.wheelDeltaX!==undefined&&(g=-1*c.wheelDeltaX/120),d.unshift(b,e,g,h),(a.event.dispatch||a.event.handle).apply(this,d)}var b=["DOMMouseScroll","mousewheel"];if(a.event.fixHooks)for(var c=b.length;c;)a.event.fixHooks[b[--c]]=a.event.mouseHooks;a.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var a=b.length;a;)this.addEventListener(b[--a],d,!1);else this.onmousewheel=d},teardown:function(){if(this.removeEventListener)for(var a=b.length;a;)this.removeEventListener(b[--a],d,!1);else this.onmousewheel=null}},a.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})})(jQuery);


/*
 * jScrollPane - v2.0.0beta12 - 2012-09-27
 * http://jscrollpane.kelvinluck.com/
 *
 * Copyright (c) 2010 Kelvin Luck
 * Dual licensed under the MIT or GPL licenses.
 */
(function(b,a,c){b.fn.jScrollPane=function(e){function d(D,O){var ay,Q=this,Y,aj,v,al,T,Z,y,q,az,aE,au,i,I,h,j,aa,U,ap,X,t,A,aq,af,am,G,l,at,ax,x,av,aH,f,L,ai=true,P=true,aG=false,k=false,ao=D.clone(false,false).empty(),ac=b.fn.mwheelIntent?"mwheelIntent.jsp":"mousewheel.jsp";aH=D.css("paddingTop")+" "+D.css("paddingRight")+" "+D.css("paddingBottom")+" "+D.css("paddingLeft");f=(parseInt(D.css("paddingLeft"),10)||0)+(parseInt(D.css("paddingRight"),10)||0);function ar(aQ){var aL,aN,aM,aJ,aI,aP,aO=false,aK=false;ay=aQ;if(Y===c){aI=D.scrollTop();aP=D.scrollLeft();D.css({overflow:"hidden",padding:0});aj=D.innerWidth()+f;v=D.innerHeight();D.width(aj);Y=b('<div class="jspPane" />').css("padding",aH).append(D.children());al=b('<div class="jspContainer" />').css({width:aj+"px",height:v+"px"}).append(Y).appendTo(D)}else{D.css("width","");aO=ay.stickToBottom&&K();aK=ay.stickToRight&&B();aJ=D.innerWidth()+f!=aj||D.outerHeight()!=v;if(aJ){aj=D.innerWidth()+f;v=D.innerHeight();al.css({width:aj+"px",height:v+"px"})}if(!aJ&&L==T&&Y.outerHeight()==Z){D.width(aj);return}L=T;Y.css("width","");D.width(aj);al.find(">.jspVerticalBar,>.jspHorizontalBar").remove().end()}Y.css("overflow","auto");if(aQ.contentWidth){T=aQ.contentWidth}else{T=Y[0].scrollWidth}Z=Y[0].scrollHeight;Y.css("overflow","");y=T/aj;q=Z/v;az=q>1;aE=y>1;if(!(aE||az)){D.removeClass("jspScrollable");Y.css({top:0,width:al.width()-f});n();E();R();w()}else{D.addClass("jspScrollable");aL=ay.maintainPosition&&(I||aa);if(aL){aN=aC();aM=aA()}aF();z();F();if(aL){N(aK?(T-aj):aN,false);M(aO?(Z-v):aM,false)}J();ag();an();if(ay.enableKeyboardNavigation){S()}if(ay.clickOnTrack){p()}C();if(ay.hijackInternalLinks){m()}}if(ay.autoReinitialise&&!av){av=setInterval(function(){ar(ay)},ay.autoReinitialiseDelay)}else{if(!ay.autoReinitialise&&av){clearInterval(av)}}aI&&D.scrollTop(0)&&M(aI,false);aP&&D.scrollLeft(0)&&N(aP,false);D.trigger("jsp-initialised",[aE||az])}function aF(){if(az){al.append(b('<div class="jspVerticalBar" />').append(b('<div class="jspCap jspCapTop" />'),b('<div class="jspTrack" />').append(b('<div class="jspDrag" />').append(b('<div class="jspDragTop" />'),b('<div class="jspDragBottom" />'))),b('<div class="jspCap jspCapBottom" />')));U=al.find(">.jspVerticalBar");ap=U.find(">.jspTrack");au=ap.find(">.jspDrag");if(ay.showArrows){aq=b('<a class="jspArrow jspArrowUp" />').bind("mousedown.jsp",aD(0,-1)).bind("click.jsp",aB);af=b('<a class="jspArrow jspArrowDown" />').bind("mousedown.jsp",aD(0,1)).bind("click.jsp",aB);if(ay.arrowScrollOnHover){aq.bind("mouseover.jsp",aD(0,-1,aq));af.bind("mouseover.jsp",aD(0,1,af))}ak(ap,ay.verticalArrowPositions,aq,af)}t=v;al.find(">.jspVerticalBar>.jspCap:visible,>.jspVerticalBar>.jspArrow").each(function(){t-=b(this).outerHeight()});au.hover(function(){au.addClass("jspHover")},function(){au.removeClass("jspHover")}).bind("mousedown.jsp",function(aI){b("html").bind("dragstart.jsp selectstart.jsp",aB);au.addClass("jspActive");var s=aI.pageY-au.position().top;b("html").bind("mousemove.jsp",function(aJ){V(aJ.pageY-s,false)}).bind("mouseup.jsp mouseleave.jsp",aw);return false});o()}}function o(){ap.height(t+"px");I=0;X=ay.verticalGutter+ap.outerWidth();Y.width(aj-X-f);try{if(U.position().left===0){Y.css("margin-left",X+"px")}}catch(s){}}function z(){if(aE){al.append(b('<div class="jspHorizontalBar" />').append(b('<div class="jspCap jspCapLeft" />'),b('<div class="jspTrack" />').append(b('<div class="jspDrag" />').append(b('<div class="jspDragLeft" />'),b('<div class="jspDragRight" />'))),b('<div class="jspCap jspCapRight" />')));am=al.find(">.jspHorizontalBar");G=am.find(">.jspTrack");h=G.find(">.jspDrag");if(ay.showArrows){ax=b('<a class="jspArrow jspArrowLeft" />').bind("mousedown.jsp",aD(-1,0)).bind("click.jsp",aB);x=b('<a class="jspArrow jspArrowRight" />').bind("mousedown.jsp",aD(1,0)).bind("click.jsp",aB);
if(ay.arrowScrollOnHover){ax.bind("mouseover.jsp",aD(-1,0,ax));x.bind("mouseover.jsp",aD(1,0,x))}ak(G,ay.horizontalArrowPositions,ax,x)}h.hover(function(){h.addClass("jspHover")},function(){h.removeClass("jspHover")}).bind("mousedown.jsp",function(aI){b("html").bind("dragstart.jsp selectstart.jsp",aB);h.addClass("jspActive");var s=aI.pageX-h.position().left;b("html").bind("mousemove.jsp",function(aJ){W(aJ.pageX-s,false)}).bind("mouseup.jsp mouseleave.jsp",aw);return false});l=al.innerWidth();ah()}}function ah(){al.find(">.jspHorizontalBar>.jspCap:visible,>.jspHorizontalBar>.jspArrow").each(function(){l-=b(this).outerWidth()});G.width(l+"px");aa=0}function F(){if(aE&&az){var aI=G.outerHeight(),s=ap.outerWidth();t-=aI;b(am).find(">.jspCap:visible,>.jspArrow").each(function(){l+=b(this).outerWidth()});l-=s;v-=s;aj-=aI;G.parent().append(b('<div class="jspCorner" />').css("width",aI+"px"));o();ah()}if(aE){Y.width((al.outerWidth()-f)+"px")}Z=Y.outerHeight();q=Z/v;if(aE){at=Math.ceil(1/y*l);if(at>ay.horizontalDragMaxWidth){at=ay.horizontalDragMaxWidth}else{if(at<ay.horizontalDragMinWidth){at=ay.horizontalDragMinWidth}}h.width(at+"px");j=l-at;ae(aa)}if(az){A=Math.ceil(1/q*t);if(A>ay.verticalDragMaxHeight){A=ay.verticalDragMaxHeight}else{if(A<ay.verticalDragMinHeight){A=ay.verticalDragMinHeight}}au.height(A+"px");i=t-A;ad(I)}}function ak(aJ,aL,aI,s){var aN="before",aK="after",aM;if(aL=="os"){aL=/Mac/.test(navigator.platform)?"after":"split"}if(aL==aN){aK=aL}else{if(aL==aK){aN=aL;aM=aI;aI=s;s=aM}}aJ[aN](aI)[aK](s)}function aD(aI,s,aJ){return function(){H(aI,s,this,aJ);this.blur();return false}}function H(aL,aK,aO,aN){aO=b(aO).addClass("jspActive");var aM,aJ,aI=true,s=function(){if(aL!==0){Q.scrollByX(aL*ay.arrowButtonSpeed)}if(aK!==0){Q.scrollByY(aK*ay.arrowButtonSpeed)}aJ=setTimeout(s,aI?ay.initialDelay:ay.arrowRepeatFreq);aI=false};s();aM=aN?"mouseout.jsp":"mouseup.jsp";aN=aN||b("html");aN.bind(aM,function(){aO.removeClass("jspActive");aJ&&clearTimeout(aJ);aJ=null;aN.unbind(aM)})}function p(){w();if(az){ap.bind("mousedown.jsp",function(aN){if(aN.originalTarget===c||aN.originalTarget==aN.currentTarget){var aL=b(this),aO=aL.offset(),aM=aN.pageY-aO.top-I,aJ,aI=true,s=function(){var aR=aL.offset(),aS=aN.pageY-aR.top-A/2,aP=v*ay.scrollPagePercent,aQ=i*aP/(Z-v);if(aM<0){if(I-aQ>aS){Q.scrollByY(-aP)}else{V(aS)}}else{if(aM>0){if(I+aQ<aS){Q.scrollByY(aP)}else{V(aS)}}else{aK();return}}aJ=setTimeout(s,aI?ay.initialDelay:ay.trackClickRepeatFreq);aI=false},aK=function(){aJ&&clearTimeout(aJ);aJ=null;b(document).unbind("mouseup.jsp",aK)};s();b(document).bind("mouseup.jsp",aK);return false}})}if(aE){G.bind("mousedown.jsp",function(aN){if(aN.originalTarget===c||aN.originalTarget==aN.currentTarget){var aL=b(this),aO=aL.offset(),aM=aN.pageX-aO.left-aa,aJ,aI=true,s=function(){var aR=aL.offset(),aS=aN.pageX-aR.left-at/2,aP=aj*ay.scrollPagePercent,aQ=j*aP/(T-aj);if(aM<0){if(aa-aQ>aS){Q.scrollByX(-aP)}else{W(aS)}}else{if(aM>0){if(aa+aQ<aS){Q.scrollByX(aP)}else{W(aS)}}else{aK();return}}aJ=setTimeout(s,aI?ay.initialDelay:ay.trackClickRepeatFreq);aI=false},aK=function(){aJ&&clearTimeout(aJ);aJ=null;b(document).unbind("mouseup.jsp",aK)};s();b(document).bind("mouseup.jsp",aK);return false}})}}function w(){if(G){G.unbind("mousedown.jsp")}if(ap){ap.unbind("mousedown.jsp")}}function aw(){b("html").unbind("dragstart.jsp selectstart.jsp mousemove.jsp mouseup.jsp mouseleave.jsp");if(au){au.removeClass("jspActive")}if(h){h.removeClass("jspActive")}}function V(s,aI){if(!az){return}if(s<0){s=0}else{if(s>i){s=i}}if(aI===c){aI=ay.animateScroll}if(aI){Q.animate(au,"top",s,ad)}else{au.css("top",s);ad(s)}}function ad(aI){if(aI===c){aI=au.position().top}al.scrollTop(0);I=aI;var aL=I===0,aJ=I==i,aK=aI/i,s=-aK*(Z-v);if(ai!=aL||aG!=aJ){ai=aL;aG=aJ;D.trigger("jsp-arrow-change",[ai,aG,P,k])}u(aL,aJ);Y.css("top",s);D.trigger("jsp-scroll-y",[-s,aL,aJ]).trigger("scroll")}function W(aI,s){if(!aE){return}if(aI<0){aI=0}else{if(aI>j){aI=j}}if(s===c){s=ay.animateScroll}if(s){Q.animate(h,"left",aI,ae)
}else{h.css("left",aI);ae(aI)}}function ae(aI){if(aI===c){aI=h.position().left}al.scrollTop(0);aa=aI;var aL=aa===0,aK=aa==j,aJ=aI/j,s=-aJ*(T-aj);if(P!=aL||k!=aK){P=aL;k=aK;D.trigger("jsp-arrow-change",[ai,aG,P,k])}r(aL,aK);Y.css("left",s);D.trigger("jsp-scroll-x",[-s,aL,aK]).trigger("scroll")}function u(aI,s){if(ay.showArrows){aq[aI?"addClass":"removeClass"]("jspDisabled");af[s?"addClass":"removeClass"]("jspDisabled")}}function r(aI,s){if(ay.showArrows){ax[aI?"addClass":"removeClass"]("jspDisabled");x[s?"addClass":"removeClass"]("jspDisabled")}}function M(s,aI){var aJ=s/(Z-v);V(aJ*i,aI)}function N(aI,s){var aJ=aI/(T-aj);W(aJ*j,s)}function ab(aV,aQ,aJ){var aN,aK,aL,s=0,aU=0,aI,aP,aO,aS,aR,aT;try{aN=b(aV)}catch(aM){return}aK=aN.outerHeight();aL=aN.outerWidth();al.scrollTop(0);al.scrollLeft(0);while(!aN.is(".jspPane")){s+=aN.position().top;aU+=aN.position().left;aN=aN.offsetParent();if(/^body|html$/i.test(aN[0].nodeName)){return}}aI=aA();aO=aI+v;if(s<aI||aQ){aR=s-ay.verticalGutter}else{if(s+aK>aO){aR=s-v+aK+ay.verticalGutter}}if(aR){M(aR,aJ)}aP=aC();aS=aP+aj;if(aU<aP||aQ){aT=aU-ay.horizontalGutter}else{if(aU+aL>aS){aT=aU-aj+aL+ay.horizontalGutter}}if(aT){N(aT,aJ)}}function aC(){return -Y.position().left}function aA(){return -Y.position().top}function K(){var s=Z-v;return(s>20)&&(s-aA()<10)}function B(){var s=T-aj;return(s>20)&&(s-aC()<10)}function ag(){al.unbind(ac).bind(ac,function(aL,aM,aK,aI){var aJ=aa,s=I;Q.scrollBy(aK*ay.mouseWheelSpeed,-aI*ay.mouseWheelSpeed,false);return aJ==aa&&s==I})}function n(){al.unbind(ac)}function aB(){return false}function J(){Y.find(":input,a").unbind("focus.jsp").bind("focus.jsp",function(s){ab(s.target,false)})}function E(){Y.find(":input,a").unbind("focus.jsp")}function S(){var s,aI,aK=[];aE&&aK.push(am[0]);az&&aK.push(U[0]);Y.focus(function(){D.focus()});D.attr("tabindex",0).unbind("keydown.jsp keypress.jsp").bind("keydown.jsp",function(aN){if(aN.target!==this&&!(aK.length&&b(aN.target).closest(aK).length)){return}var aM=aa,aL=I;switch(aN.keyCode){case 40:case 38:case 34:case 32:case 33:case 39:case 37:s=aN.keyCode;aJ();break;case 35:M(Z-v);s=null;break;case 36:M(0);s=null;break}aI=aN.keyCode==s&&aM!=aa||aL!=I;return !aI}).bind("keypress.jsp",function(aL){if(aL.keyCode==s){aJ()}return !aI});if(ay.hideFocus){D.css("outline","none");if("hideFocus" in al[0]){D.attr("hideFocus",true)}}else{D.css("outline","");if("hideFocus" in al[0]){D.attr("hideFocus",false)}}function aJ(){var aM=aa,aL=I;switch(s){case 40:Q.scrollByY(ay.keyboardSpeed,false);break;case 38:Q.scrollByY(-ay.keyboardSpeed,false);break;case 34:case 32:Q.scrollByY(v*ay.scrollPagePercent,false);break;case 33:Q.scrollByY(-v*ay.scrollPagePercent,false);break;case 39:Q.scrollByX(ay.keyboardSpeed,false);break;case 37:Q.scrollByX(-ay.keyboardSpeed,false);break}aI=aM!=aa||aL!=I;return aI}}function R(){D.attr("tabindex","-1").removeAttr("tabindex").unbind("keydown.jsp keypress.jsp")}function C(){if(location.hash&&location.hash.length>1){var aK,aI,aJ=escape(location.hash.substr(1));try{aK=b("#"+aJ+', a[name="'+aJ+'"]')}catch(s){return}if(aK.length&&Y.find(aJ)){if(al.scrollTop()===0){aI=setInterval(function(){if(al.scrollTop()>0){ab(aK,true);b(document).scrollTop(al.position().top);clearInterval(aI)}},50)}else{ab(aK,true);b(document).scrollTop(al.position().top)}}}}function m(){if(b(document.body).data("jspHijack")){return}b(document.body).data("jspHijack",true);b(document.body).delegate("a[href*=#]","click",function(s){var aI=this.href.substr(0,this.href.indexOf("#")),aK=location.href,aO,aP,aJ,aM,aL,aN;if(location.href.indexOf("#")!==-1){aK=location.href.substr(0,location.href.indexOf("#"))}if(aI!==aK){return}aO=escape(this.href.substr(this.href.indexOf("#")+1));aP;try{aP=b("#"+aO+', a[name="'+aO+'"]')}catch(aQ){return}if(!aP.length){return}aJ=aP.closest(".jspScrollable");aM=aJ.data("jsp");aM.scrollToElement(aP,true);if(aJ[0].scrollIntoView){aL=b(a).scrollTop();aN=aP.offset().top;if(aN<aL||aN>aL+b(a).height()){aJ[0].scrollIntoView()}}s.preventDefault()
})}function an(){var aJ,aI,aL,aK,aM,s=false;al.unbind("touchstart.jsp touchmove.jsp touchend.jsp click.jsp-touchclick").bind("touchstart.jsp",function(aN){var aO=aN.originalEvent.touches[0];aJ=aC();aI=aA();aL=aO.pageX;aK=aO.pageY;aM=false;s=true}).bind("touchmove.jsp",function(aQ){if(!s){return}var aP=aQ.originalEvent.touches[0],aO=aa,aN=I;Q.scrollTo(aJ+aL-aP.pageX,aI+aK-aP.pageY);aM=aM||Math.abs(aL-aP.pageX)>5||Math.abs(aK-aP.pageY)>5;return aO==aa&&aN==I}).bind("touchend.jsp",function(aN){s=false}).bind("click.jsp-touchclick",function(aN){if(aM){aM=false;return false}})}function g(){var s=aA(),aI=aC();D.removeClass("jspScrollable").unbind(".jsp");D.replaceWith(ao.append(Y.children()));ao.scrollTop(s);ao.scrollLeft(aI);if(av){clearInterval(av)}}b.extend(Q,{reinitialise:function(aI){aI=b.extend({},ay,aI);ar(aI)},scrollToElement:function(aJ,aI,s){ab(aJ,aI,s)},scrollTo:function(aJ,s,aI){N(aJ,aI);M(s,aI)},scrollToX:function(aI,s){N(aI,s)},scrollToY:function(s,aI){M(s,aI)},scrollToPercentX:function(aI,s){N(aI*(T-aj),s)},scrollToPercentY:function(aI,s){M(aI*(Z-v),s)},scrollBy:function(aI,s,aJ){Q.scrollByX(aI,aJ);Q.scrollByY(s,aJ)},scrollByX:function(s,aJ){var aI=aC()+Math[s<0?"floor":"ceil"](s),aK=aI/(T-aj);W(aK*j,aJ)},scrollByY:function(s,aJ){var aI=aA()+Math[s<0?"floor":"ceil"](s),aK=aI/(Z-v);V(aK*i,aJ)},positionDragX:function(s,aI){W(s,aI)},positionDragY:function(aI,s){V(aI,s)},animate:function(aI,aL,s,aK){var aJ={};aJ[aL]=s;aI.animate(aJ,{duration:ay.animateDuration,easing:ay.animateEase,queue:false,step:aK})},getContentPositionX:function(){return aC()},getContentPositionY:function(){return aA()},getContentWidth:function(){return T},getContentHeight:function(){return Z},getPercentScrolledX:function(){return aC()/(T-aj)},getPercentScrolledY:function(){return aA()/(Z-v)},getIsScrollableH:function(){return aE},getIsScrollableV:function(){return az},getContentPane:function(){return Y},scrollToBottom:function(s){V(i,s)},hijackInternalLinks:b.noop,destroy:function(){g()}});ar(O)}e=b.extend({},b.fn.jScrollPane.defaults,e);b.each(["mouseWheelSpeed","arrowButtonSpeed","trackClickSpeed","keyboardSpeed"],function(){e[this]=e[this]||e.speed});return this.each(function(){var f=b(this),g=f.data("jsp");if(g){g.reinitialise(e)}else{b("script",f).filter('[type="text/javascript"],:not([type])').remove();g=new d(f,e);f.data("jsp",g)}})};b.fn.jScrollPane.defaults={showArrows:false,maintainPosition:true,stickToBottom:false,stickToRight:false,clickOnTrack:true,autoReinitialise:false,autoReinitialiseDelay:500,verticalDragMinHeight:0,verticalDragMaxHeight:99999,horizontalDragMinWidth:0,horizontalDragMaxWidth:99999,contentWidth:c,animateScroll:false,animateDuration:300,animateEase:"linear",hijackInternalLinks:false,verticalGutter:4,horizontalGutter:4,mouseWheelSpeed:0,arrowButtonSpeed:0,arrowRepeatFreq:50,arrowScrollOnHover:false,trackClickSpeed:0,trackClickRepeatFreq:70,verticalArrowPositions:"split",horizontalArrowPositions:"split",enableKeyboardNavigation:true,hideFocus:false,keyboardSpeed:0,initialDelay:300,speed:30,scrollPagePercent:0.8}})(jQuery,this);


/*! matchMedia() polyfill - Test a CSS media type/query in JS. Authors & copyright (c) 2012: Scott Jehl, Paul Irish, Nicholas Zakas. Dual MIT/BSD license */
/*! NOTE: If you're already including a window.matchMedia polyfill via Modernizr or otherwise, you don't need this part */
window.matchMedia=window.matchMedia||function(a){"use strict";var c,d=a.documentElement,e=d.firstElementChild||d.firstChild,f=a.createElement("body"),g=a.createElement("div");return g.id="mq-test-1",g.style.cssText="position:absolute;top:-100em",f.style.background="none",f.appendChild(g),function(a){return g.innerHTML='&shy;<style media="'+a+'"> #mq-test-1 { width: 42px; }</style>',d.insertBefore(f,e),c=42===g.offsetWidth,d.removeChild(f),{matches:c,media:a}}}(document);

/*! Respond.js v1.1.0: min/max-width media query polyfill. (c) Scott Jehl. MIT/GPLv2 Lic. j.mp/respondjs  */
(function(a){"use strict";function x(){u(!0)}var b={};if(a.respond=b,b.update=function(){},b.mediaQueriesSupported=a.matchMedia&&a.matchMedia("only all").matches,!b.mediaQueriesSupported){var q,r,t,c=a.document,d=c.documentElement,e=[],f=[],g=[],h={},i=30,j=c.getElementsByTagName("head")[0]||d,k=c.getElementsByTagName("base")[0],l=j.getElementsByTagName("link"),m=[],n=function(){for(var b=0;l.length>b;b++){var c=l[b],d=c.href,e=c.media,f=c.rel&&"stylesheet"===c.rel.toLowerCase();d&&f&&!h[d]&&(c.styleSheet&&c.styleSheet.rawCssText?(p(c.styleSheet.rawCssText,d,e),h[d]=!0):(!/^([a-zA-Z:]*\/\/)/.test(d)&&!k||d.replace(RegExp.$1,"").split("/")[0]===a.location.host)&&m.push({href:d,media:e}))}o()},o=function(){if(m.length){var a=m.shift();v(a.href,function(b){p(b,a.href,a.media),h[a.href]=!0,setTimeout(function(){o()},0)})}},p=function(a,b,c){var d=a.match(/@media[^\{]+\{([^\{\}]*\{[^\}\{]*\})+/gi),g=d&&d.length||0;b=b.substring(0,b.lastIndexOf("/"));var h=function(a){return a.replace(/(url\()['"]?([^\/\)'"][^:\)'"]+)['"]?(\))/g,"$1"+b+"$2$3")},i=!g&&c;b.length&&(b+="/"),i&&(g=1);for(var j=0;g>j;j++){var k,l,m,n;i?(k=c,f.push(h(a))):(k=d[j].match(/@media *([^\{]+)\{([\S\s]+?)$/)&&RegExp.$1,f.push(RegExp.$2&&h(RegExp.$2))),m=k.split(","),n=m.length;for(var o=0;n>o;o++)l=m[o],e.push({media:l.split("(")[0].match(/(only\s+)?([a-zA-Z]+)\s?/)&&RegExp.$2||"all",rules:f.length-1,hasquery:l.indexOf("(")>-1,minw:l.match(/\(min\-width:[\s]*([\s]*[0-9\.]+)(px|em)[\s]*\)/)&&parseFloat(RegExp.$1)+(RegExp.$2||""),maxw:l.match(/\(max\-width:[\s]*([\s]*[0-9\.]+)(px|em)[\s]*\)/)&&parseFloat(RegExp.$1)+(RegExp.$2||"")})}u()},s=function(){var a,b=c.createElement("div"),e=c.body,f=!1;return b.style.cssText="position:absolute;font-size:1em;width:1em",e||(e=f=c.createElement("body"),e.style.background="none"),e.appendChild(b),d.insertBefore(e,d.firstChild),a=b.offsetWidth,f?d.removeChild(e):e.removeChild(b),a=t=parseFloat(a)},u=function(a){var b="clientWidth",h=d[b],k="CSS1Compat"===c.compatMode&&h||c.body[b]||h,m={},n=l[l.length-1],o=(new Date).getTime();if(a&&q&&i>o-q)return clearTimeout(r),r=setTimeout(u,i),void 0;q=o;for(var p in e)if(e.hasOwnProperty(p)){var v=e[p],w=v.minw,x=v.maxw,y=null===w,z=null===x,A="em";w&&(w=parseFloat(w)*(w.indexOf(A)>-1?t||s():1)),x&&(x=parseFloat(x)*(x.indexOf(A)>-1?t||s():1)),v.hasquery&&(y&&z||!(y||k>=w)||!(z||x>=k))||(m[v.media]||(m[v.media]=[]),m[v.media].push(f[v.rules]))}for(var B in g)g.hasOwnProperty(B)&&g[B]&&g[B].parentNode===j&&j.removeChild(g[B]);for(var C in m)if(m.hasOwnProperty(C)){var D=c.createElement("style"),E=m[C].join("\n");D.type="text/css",D.media=C,j.insertBefore(D,n.nextSibling),D.styleSheet?D.styleSheet.cssText=E:D.appendChild(c.createTextNode(E)),g.push(D)}},v=function(a,b){var c=w();c&&(c.open("GET",a,!0),c.onreadystatechange=function(){4!==c.readyState||200!==c.status&&304!==c.status||b(c.responseText)},4!==c.readyState&&c.send(null))},w=function(){var b=!1;try{b=new a.XMLHttpRequest}catch(c){b=new a.ActiveXObject("Microsoft.XMLHTTP")}return function(){return b}}();n(),b.update=n,a.addEventListener?a.addEventListener("resize",x,!1):a.attachEvent&&a.attachEvent("onresize",x)}})(this);




var TAB = {

	isHome: false,	// is at home page
	isScrolling: true,	// page is scrolling (from clicking a nav item)
	iOSVersion: 0,

	deepLinks:
	[
		['mission', 'breakthrough', 'founding'],
		['powertothepeople', 'different', 'soundscience'],
		['answerquestions', 'improveworkplaces', 'improvesociety']
	],
	targets:
	[
		['mission', 'breakthrough', 'founding'],
		['powertothepeople', 'different', 'soundscience'],
		['answerquestions', 'improveworkplaces', 'improvesociety']
	],

	init: function() {
		var root = this;
		
		// detect for ios
		if (/iP(hone|od|ad)/.test(navigator.platform)) {
		    var v = (navigator.appVersion).match(/OS (\d+)_(\d+)_?(\d+)?/);
		    this.iOSVersion = parseInt(v[1], 10);
		}
		
		// if ios, then turn off hovers
		if (this.iOSVersion > 0)
			$('body').removeClass('canhover');
		
		// set page height to window height
		// $('#page').height($(window).height());
		
		this.Debug.init(root);

		this.Sections.init(root);
		this.Nav.init(root);
		this.Scrolling.init(root);
		this.Detail.init(root);
		this.Carousel.init(root);
		this.DeepLink.init(root);
		// this.Triggers.init(root);
		
		 
		$('body').addClass('loaded');
		
		// for testing purposes only
/* 		this.Detail.show('facebook'); */
	},
	
	
	/*
	Content Sections
	*/
	Sections: {

		root: null,
		current: -1,
		verticalSpeed: 1500,
		horizontalSpeed: 750,
		verticalEasing: 'easeInOutExpo',
		horizontalEasing: 'easeOutExpo',
	
		init: function(root) {
			this.root = root;
			var ptr = this;

			// duplicate each block to use to determine height later
			this.duplicateBlocks();
			
			// update sizes and positions when window is resized
			$(window).on('throttledresize', function() { ptr.redraw() });
			this.redraw();
		},
		
		// duplicate hidden content blocks to get accurate heights later
		duplicateBlocks: function() {
			$('article section .content').each(function(index) {
				// clone the block and call it a dupe
				var $dupe = $(this).clone().addClass('dupe');
				// add navcontainer, this fixes the fact that ie8 cannot handle <nav> correctly
				$dupe.find('nav').wrap('<div class="navcontainer" />')
				// remove dupe's aside if it exists
				$dupe.find('aside').remove();
				// add dupe to page
				$dupe.appendTo($(this).parent());
			});
		},
		
		// redraw the main sections anytime the browser resizes
		redraw: function() {

			var ptr = this;
			var h = $(window).height();
			var w = $(window).width();
			 
			// set each section to size of window
			$('section').height(h);
			$('section').width(w);
			
			// // update height of page
			if (this.root.isHome)
				$('#page').height(h);
			else
			 	$('#page').height(h * 9);

			// // // keep content centered vertically
			this.centerContent();
			
			// // // keep background image sized to fit window
			this.resizeBackgrounds();
		},
		
		// vertically center section content
		centerContent: function() {
			var ptr = this;
			
			// home section
			$('#home section .info').each(function() {
				var content = $(this).height();
				var section = $(this).parent().height();
				var nav = 141;
				var gap = (section - (nav + content)) / 2;
				var top = gap;

				// make sure at least minimum distance from top
				var min = 0;
				if (top < min)
					top = min;

				$(this).css('top', top);
			});
			
			// all other sections
			$('article section .content').each(function() {
				var self = this;
				
				// ignore dupes
				if ($(this).hasClass('dupe'))
					return;

				var blockHeight = $(this).siblings('.dupe').find('.block').height();
				var content = $(this).siblings('.dupe').height();
				
				var section = $(this).parent().height();
				var windowH = $(window).height();
				var margin = parseInt($(this).css('margin-left'));
				var nav = 121;
				var gap = (section - (nav + content)) / 2;
				var top = nav + gap;

				// make sure at least minimum distance from top
				var min = nav + (margin / 2);
				var block = $(this).find('.block');

				// difference between min and top
				var diff = min - top;
				if (top < min) {

					// update scrollbar height
					block.css('height', blockHeight - (2 * diff)).jScrollPane({
						clickOnTrack: false,
						hideFocus: true
					});

					top = min;
				} else {
					// restore full block height
					block.css('height', blockHeight);

					// remove scrollbar
					if (block.data('jsp'))
						block.data('jsp').reinitialise();
				}

				$(this).css('top', top);
				
				// check for special layered images and reposition and resize
				$(this).find('.layered').each(function() {
					// original img w and h
					var origw = parseInt($(this).data('width'));
					var origh = parseInt($(this).data('height'));
					
					// new values
					var newh = section - nav - gap;
					var newmargin = gap / -2;

					// if top does not reach min, set height of image to same as left content
					if (diff > 0) {
						newh = $(self).height();
						newmargin = 0;
					}
					
					// limit height to original img height
					if (newh > origh)
						newh = origh;

					// width is always proportional to height
					var neww = newh * origw / origh;
					
					// make it so
					$(this).css('height', newh);
					$(this).css('width', neww);
					$(this).css('margin-top', newmargin);
				});
				
				// for breakthrough only, if height of browser is too short, hide aside text and button
				if ($(this).parent().attr('id') == "breakthrough") {
					if (windowH < 750)
						$(this).find('.layered .inner').hide();
					else
						$(this).find('.layered .inner').show();
				}
			});
		},
		
		resizeBackgrounds: function() {
			var ptr = this;
			
			var w = $(window).width();
			if (w < 1024)
				w = 1024;
			var h = $(window).height();
			
			$('article section .bg img').each(function() {
				var ratio = $(this).attr('width') / $(this).attr('height');

				var imgH = w / ratio;
				
				if (imgH < h) {
					// height-dominant
					$(this).css('height', h);
					var imgW = w * (h / imgH);
					$(this).css('width', imgW);
					
					// if forced left align, then keep left edge at zero
					if ($(this).parent().data('align') == "left") {
						$(this).css('left', 0);
					} else {
						// by default center the bg image horizontally
						$(this).css('left', -.5 * (imgW - w));
					}

				} else {
					// width-dominant
					$(this).css('height', imgH);
					$(this).css('width', w);
					$(this).css('left', 0);
				}
			});
		},

		// go to a specific section
		goto: function(mainId, subId) {
			var ptr = this;
			var w = $(window).width();
			var h = $(window).height();

			// update nav
			this.root.Nav.setActive(mainId, subId);
			
			// recenter content
			this.centerContent();

			// if starting from home, slide up, otherwise just slide to section
			if (this.root.isHome) {
				this.root.isHome = false;

				this.root.isScrolling = true;
				
				// position the selected section to top
				$('#page').addClass('offset' + mainId + '-' + subId);
				
				// slide content up
				$('#content').css('top', h).stop().animate({top: 0}, this.verticalSpeed, this.verticalEasing);

				// slide home up and then hide it
				$('#home').stop().animate({top: -1 * h}, this.verticalSpeed, this.verticalEasing, function() {
					$(this).hide();
				});
				
				// slide nav images down and shrink them
				$('header .main li a img').each(function() {
					var p = .85;
					var w = $(this).width() * p;
					var h = $(this).height() * p;
					$(this).delay(500).animate({
						'margin-top': 91,
						width: w,
						height: h
					}, 500);
				});
				
				// slide header nav up
				$('header').animate({bottom: h - 72}, this.verticalSpeed, this.verticalEasing, function() {
					// swap position from bottom to top
					$('header').css('top', -79);
					
					// mark header as being on top
					$('header').addClass('top');
					
					// update height of page which creates the scrollbar
					$('#page').height(h * 9);
					
					// slide subnav down
					$('header .sub').css('top', 0).show().animate({top: 65}, this.verticalSpeed, this.verticalEasing);

					// jump to specified section
					$('#page').removeClass();
					ptr.contentScroll(mainId, subId, true);

					// init waypoints for each subsection
					ptr.root.Waypoints.init(ptr.root);
					
					// no longer scroll - this needs to be after waypoints have inited
					ptr.root.isScrolling = false;
					
					// show homebutton
					$('#homebutton').addClass('enabled');
					
					// make sure trigger happens
					ptr.root.Triggers.scrollHandler();
				});
			} else {
				// slide to first subsection of selected section
				this.contentScroll(mainId, subId, false);
			}
		},
		
		// actually start the animation
		contentScroll: function(mainId, subId, instant) {
			var target = '#' + this.root.targets[mainId][subId];
			if (target)
				this.root.Scrolling.scroll(target, instant);
		}

	},
	
	
	/*
	Navigation
	*/
	Nav: {
	
		root: null,
		elHeader: 'header',
		elMainItems: 'header .main li',
		elSubNavs: 'header .sub ul',
		elSubItems: 'header .sub li',
		
		init: function(root) {
			this.root = root;
			var ptr = this;
			
			// click a main nav item to change sections
			$(this.elMainItems).each(function(index) {
				$(this).click(function(e) {
/* 				$(this).bind('click touchend', function(e) { */
					// set this item as active
					ptr.setActive(index, 0);
					
					// update hash
					ptr.root.DeepLink.set(index, 0);
					
					// change sections
					ptr.root.Sections.goto(index, 0);
				});

				// disable anchor
				$(this).find('a').click(function(e) {
					e.preventDefault();
				});
			});
			
			// mouseovers, unless ios
			if (this.root.iOSVersion <= 0) {
				// mouse over each main nav displays its sub nav
				$(this.elMainItems).each(function(index) {
					// show related subnav on mouse over
					$(this).mouseover(function() {
						$(this).siblings().removeClass('open').addClass('closed');
						$(this).removeClass('closed').addClass('open');
					});
					// go back to current subnav on mouse out
					$(this).mouseout(function() {
						$(this).siblings().removeClass('open').removeClass('closed');
						$(this).removeClass('open').removeClass('closed');
					});
				});
			}

			// keep nav full width when window is resized
			$(window).on('throttledresize', function() { ptr.redraw(); });
			this.redraw();
		},
		
		// set the active main nav item
		// subId is optional id for active subnav item
		setActive: function(id, subId) {
			// save specified id as current section
			this.root.Sections.current = id;
			
			// highlight this nav item
			$(this.elMainItems).removeClass('active').eq(id).addClass('active');
			
			// show correct sub nav
			this.updateSubNav(id, subId);
		},
		
		updateSubNav: function(sectionId, subId) {
			var ptr = this;
			
			// hide all subnavs
			$(this.elSubNavs).hide();
			
			// show the specified subnav
			var nav = $(this.elSubNavs).eq(parseInt(sectionId));
			nav.show();

			// highlight the specified subnav item
			if (parseInt(subId) >= 0) {
				// remove all highlights
				$(this.elSubNavs).find('li').removeClass('active');

				// set new highlight
				nav.find('li').eq(subId).addClass('active');
				
				// save deep link to this page
				ptr.root.DeepLink.set(sectionId, subId);
			}
		},
		
		redraw: function() {
			var w = $(window).width();
			var remainder = w;
		
/*
			$(this.elMainItems).each(function(index) {
				if (index < 2)
					remainder -= $(this).width();
				else
					$(this).width(remainder);
			});
*/
		}

	},
	
	
	/*
	 * Scrolling
	 */
	Scrolling: {
	
		root: null,
		elScroll: "html, body",
	
		init: function(root) {
			this.root = root;
			var ptr = this;
			
			// http://www.zachstronaut.com/posts/2009/01/18/jquery-smooth-scroll-bugs.html
			$(this.elScroll).each(function () {
				var initScrollTop = $(this).attr('scrollTop');
				$(this).attr('scrollTop', initScrollTop + 1);
				if ($(this).attr('scrollTop') == initScrollTop + 1) {
					scrollElement = this.nodeName.toLowerCase();
					$(this).attr('scrollTop', initScrollTop);
					return false;
				}
			});

			// Smooth scrolling for internal links
			$("a[href^='#']").click(function(event) {
				event.preventDefault();
				
				var $this = $(this),
				target = this.hash,
				$target = $(target);
				
				// if no target, bye
				if (!target)
					return;
				
				// update active highlights
				ptr.root.Nav.setActive($this.parent().parent().data('id'), $this.parent().data('id'));
				
				// animate
				ptr.scroll(target);
			});
		},
		
		// scroll the page to the target element
		// instant is boolean
		scroll: function(target, instant) {
			var ptr = this;
			var time = 1500;
			
			if (instant)
				time = 0;
			
			// if no target, bye
			if (target == undefined || target == "")
				return;

			// don't change isScrolling if instant
			if (!instant)
				this.root.isScrolling = true;

			// for ios below 6, remove fixed position because of ios bug
			if (this.root.iOSVersion > 0 && this.root.iOSVersion < 6)
				$(this.elScroll).removeClass('fixed').addClass('unfixed');

			$(this.elScroll).stop().animate({
				'scrollTop': $(target).offset().top
			}, time, 'easeInOutExpo', function() {
				//window.location.hash = target;

				// don't change isScrolling if instant
				if (!instant)
					ptr.root.isScrolling = false;

				// for ios below 6, set header back to fixed position
				if (ptr.root.iOSVersion > 0 && ptr.root.iOSVersion < 6)
					setTimeout(function() { $('.unfixed').addClass('fixed').removeClass('unfixed'); }, 50);
			});
		}
	
	},
	
	
	/*
	Waypoints
	*/
	Waypoints: {
	
		root: null,
		elSubMenu: 'header .sub li',
	
		init: function(root) {
			this.root = root;
			var ptr = this;
			
			$('#content section').waypoint(function(direction) {
				// ignore waypoints while page is auto scrolling
				if (ptr.root.isScrolling)
					return;
			
				var $active = $(this);
				
				// get the active element
				if (direction === "up")
					$active = $active.prev();
				if (!$active.length) $active = $active.end();

				$('header .sub .active').removeClass('active');
				var anchor = $('a[href=#' + $active.attr('id') + ']');
				if (anchor) {
					// update main nav
					var id = anchor.parent().parent().data('id');
					ptr.root.Nav.setActive(id, anchor.parent().data('id'));
				}
			}, { offset: '50%' });
			
			// solve for ipad bug where waypoints sometimes stop working
			if (ptr.root.iOSVersion > 0)
				setInterval(function() { $.waypoints('refresh'); }, 250);
		},

	},
	
	
	/*
	Detail Pages
	*/
	Detail: {
		
		slideSpeed: 1000,
		slideEasing: 'easeOutExpo',
		elLinks: 'article section nav li, #details nav li',
		elMoreLinks: 'section .more a',
		elPage: '#page',
		elHeader: 'header',
		elContainer: '#details',
		elPages: '#details section',
		elClose: '#details .close',
		elNav: '#details nav',
		elNavs: '#details nav ul',
		elBox: '#details .box',
		
		init: function(root) {
			this.root = root;
			var ptr = this;
			
			// activate nav links
			$(this.elLinks).each(function(index) {
				var target = $(this).data('id');
				if (target) {
					$(this).click(function() {
						ptr.show(target);
					});
				}
			});
			
			// activate more links
			$(this.elMoreLinks).each(function(index) {
				var target = $(this).data('id');
				if (target) {
					$(this).attr('href', '').click(function(e) {
						ptr.show(target);
						e.preventDefault();
						return false;
					});
				}
			});
			
			// activate close button
			$(this.elClose).click(function() {
				ptr.hide();
			});
		},
		
		show: function(id) {
			var ptr = this;
			
			var index = $(this.elPages).index($('#' + id));
			var page = $(this.elPages)[index];
			var nav;
			var w = $(window).width();
			
			if (page) {
				// show correct nav
				$(this.elNavs).each(function(index) {
					if ($(page).data('nav') == index) {
						// set active nav item
						$(this).find('li').each(function(index) {
							if ($(this).data('id') == id)
								$(this).addClass('active');
							else
								$(this).removeClass('active');
						});
						// show nav
						$(this).show();
					} else {
						$(this).hide();
					}
				});
				
				// if detail modal is not open, transition to show it
				if (!$('body').hasClass('detail')) {
					// show page
					$(page).show();
					
					// set color for back button
					$(this.elClose).removeClass('detail-philosophy detail-impact detail-story');
					var sectionClass = $(page).attr('class');
					if (sectionClass)
						$(this.elClose).addClass(sectionClass);
						
					// hide homebutton
					$('#homebutton').removeClass('enabled');

					// slide out content
					$(this.elPage).animate({left:-w}, this.slideSpeed, this.slideEasing);
					$(this.elHeader).animate({left:-w}, this.slideSpeed, this.slideEasing);
					
					// slide in detail container
					$(this.elContainer).css('left', w).show().animate({left:-1}, this.slideSpeed, this.slideEasing, function() {
						// disable the page scrolling
						$('body').addClass('detail');
						
						// ios scroll disable
						if (ptr.root.iOSVersion > 0) {
							//uses document because document will be topmost level in bubbling
							$(document).on('touchmove',function(e){
								e.preventDefault();
							});
							
							// get heights of content and window
							var margin = parseInt($(page).find('.content').css('margin-top'));
							var contentHeight = margin + $(page).find('.content').height();
							var windowHeight = $(window).height();
							
							// if content is taller than window, allow for scrolling of content
							if (contentHeight > windowHeight) {
								//uses body because jquery on events are called off of the element they are
								//added to, so bubbling would not work if we used document instead.
								$('body').on('touchstart','.scrollable',function(e) {
									if (e.currentTarget.scrollTop === 0) {
										e.currentTarget.scrollTop = 1;
									} else if (e.currentTarget.scrollHeight === e.currentTarget.scrollTop + e.currentTarget.offsetHeight) {
										e.currentTarget.scrollTop -= 1;
									}
								});
								//prevents preventDefault from being called on document if it sees a scrollable div
								$('body').on('touchmove','.scrollable',function(e) {
									e.stopPropagation();
								});
							}
						}
					});
				} else {
					// detail modal already open so just show new page
					$(this.elPages).fadeOut(500);
					$(page).delay(500).fadeIn(250);
				}
			}
		},
		
		hide: function() {
			var ptr = this;
			var w = $(window).width();
			
			// allow page scrolling again
			$('body').removeClass('detail');

			// ios scroll reenable
			if (this.root.iOSVersion > 0) {
				$(document).off('touchmove');
				$('body').off('touchstart touchmove');
			}
			
			$(this.elPage).animate({left:0}, this.slideSpeed, this.slideEasing);
			$(this.elHeader).animate({left:0}, this.slideSpeed, this.slideEasing);
			$(this.elContainer).animate({left:w}, this.slideSpeed, this.slideEasing, function() {
				$(ptr.elPages).hide();
				$(this).hide();
				
				// show homebutton
				$('#homebutton').addClass('enabled');
			});
		}
		
	},


	/* Carousel */
	Carousel: {

		root: null,
		elCarousel: '.carousel',
		elContainer: '.carousel .container',
		elControls: '.carousel .controls',
		elArrows: '.carousel .arrows',
		carousels: [],
		
		init: function(root) {
			this.root = root;
			var ptr = this;

			$(this.elCarousel).each(function(index) {
				var instance = new CarouselInstance();
				instance.init(index, this);
				ptr.carousels.push(instance);
			});
		},

		// pass this on to the instance
		go: function(index, slide) {
			if (this.carousels[index])
				this.carousels[index].go(slide);
		}
	
	},
	
	
	/*
	Deep Link
	*/
	DeepLink: {
	
		root: null,
		separator: '/',
	
		init: function(root) {
			this.root = root;
			var ptr = this;
			
			// try to load existing hash
			setTimeout(function() { ptr.get() }, 500);
		},
		
		set: function(mainId, subId) {
/* 			window.location.hash = this.separator + this.root.deepLinks[mainId][subId] + this.separator; */
			window.location.replace(window.location.protocol + './' + window.location.host + 'mission.html#' + this.root.deepLinks[mainId][subId] + '');
		},
		
		get: function() {
			if (window.location.hash) {
				var hash = window.location.hash.substring(2);
				var hashArray = hash.split(this.separator);

				for (var i = 0; i < this.root.deepLinks.length; i++) {
					var subArray = this.root.deepLinks[i];
					for (var j = 0; j < subArray.length; j++) {
						if (hashArray[0] == subArray[j]) {
							this.root.Sections.goto(i, j);
							return;
						}
					}
				}
				
				// if no match, get rid of the hash
				window.location.hash = "";
			}
		}
	
	},
	
	
	/*
	Triggers for animating elements when scrolling
	*/
	Triggers: {
	
		root: null,

		// elements that get animated
		elements: {
			// one time animations
			"trigger": [
				{'selector':'#mission'},
				{'selector':'#breakthrough'},
				{'selector':'#founding'},
				{'selector':'#people'},
				{'selector':'#different'},
				{'selector':'#science'},
				{'selector':'#questions'},
				{'selector':'#workplaces'},
				{'selector':'#society'}
			]
		},
	
		init: function(root) {
			this.root = root;
			var ptr = this;

/*
			// check for css animation support
			this.cssAnimation = Modernizr.cssanimations;
*/
			
/*
			// if ios, turn off css animation for better perfomance
			var iOS = (navigator.userAgent.match(/(iPad|iPhone|iPod)/i) ? true : false);
			if (iOS)
				this.cssAnimation = false;
*/
			// no triggers for ios for better performance
			if (this.root.iOSVersion > 0)
				return;

			// init pre-triggered positions
			var els = this.elements;
			var $el;
			for (var i = 0; i < els.trigger.length; i++) {
				$el = $(els.trigger[i].selector);
				$el.find('.content h1').css('margin-left', -1000);
				$el.find('.content .block').css('margin-left', -1000);
			}
				
			// handle scroll event
			$(window).scroll(function() { ptr.scrollHandler() });
		},
		
		scrollHandler: function() {
			var els = this.elements;
			var elObj;
			
			// check each element to see if it should be triggered
			for (var i = 0; i < els.trigger.length; i++) {
				elObj = els.trigger[i];
				if (this.atTrigger(elObj) == true)
					this.doAnimate(elObj);
			}
		},
		
		// check if an element is at its trigger point for one time animations
		atTrigger: function(elObj) {
			var el = $(elObj.selector);
			
			// if already animated, skip this
			if (el.data('triggered'))
				return false;
	
			// scrolled at or past the element
			var trigger = elObj.ratio == undefined ? .66 : elObj.ratio;
			
			if ($(window).scrollTop() > el.offset().top - ($(window).height() * trigger)) {
				// if element is already off the screen, don't trigger
				var elBottom = el.offset().top + el.height();
				var winTop = $(window).scrollTop();
	
				if (winTop > elBottom)
					return false;
				else
					return true;
			}
			
			return false;
		},
		
		// start one-time animations
		doAnimate: function(elObj) {
			var el = $(elObj.selector);
			
			// mark this as having been triggered
			el.data('triggered', true);
			
			// animate
			el.find('.content h1').delay(250).animate({"margin-left": 0}, 750, 'easeOutExpo');
			el.find('.content .block').delay(500).animate({"margin-left": 0}, 750, 'easeOutExpo');
		},
	
	},
	
	
	Debug: {
	
		root: null,
		allow: false,
	
		init: function(root) {
			this.root = root;
			
			if (this.allow) {
				$('body').append('<div id="debug">..<br></div>');
				$('body').append('<style>#debug { background:red; position:fixed; top:0; left:0; z-index:999999; }</style>');
			}
		},
		
		log: function(str) {
			if (this.allow) {
				$('#debug').append(str + '<br>');
			}
		}
	}
	
}; /* End TAB */




/* Carousel Instance */
CarouselInstance = function() {};
CarouselInstance.prototype = {

	interval: null,
	current: 0,
	total: 0,
	instance: null,
	index: -1,
	delay: 0,
	
	init: function(index, carousel) {
		this.index = index;
		this.instance = $(carousel);
		
		// set height based on data attr
		if (this.instance.data('height'))
			this.instance.css('height', this.instance.data('height'));
		
		// number of seconds between auto animation: if zero, then disable
		this.delay = this.instance.data('rotatedelay') ? this.instance.data('rotatedelay') * 1000 : 0;
		
		this.current = 0;
		this.total = this.instance.find('.item').length;
		this.initPositions();
		
		// controls and rotating only if more than 1 item
		if (this.total > 1) {
			this.initControls();
			this.start();
		} else {
			// remove arrows
			this.instance.find('.arrows').remove();
		}
	},
	
	// place each slide next to each other horizontally
	initPositions: function() {
		// position each item
		var items = this.instance.find('.item');
		items.each(function(index) {
			$(this).css('left', (index * 100) + '%');
		});
	},
	
	// populate carousel nav controls
	initControls: function() {
		var ptr = this;
		
		// nav
		for (var i = 0; i < this.total; i++) {
			this.instance.find('.controls ul').append('<li><a href="javascript:TAB.Carousel.go(' + this.index + ', ' + i + ')">&bull;</a></li>');
		}
		this.updateNav();

		// arrows
		this.instance.find('.leftarrow').click(function() {
			ptr.prev();
		});
		this.instance.find('.rightarrow').click(function() {
			ptr.next();
		});
	},
	
	// update height of carousel based on width, when browser size changes
	updateSize: function() {
		var maxW = this.instance.data('maxwidth');
		var maxH = this.instance.data('maxheight');
		if (maxW != undefined && maxH != undefined) {
			var h = Math.floor(maxH / maxW * this.instance.width());
			this.instance.css('height', h);
			
			// optionally match height for another element
			var offset = parseInt(this.instance.data('heightoffset'));
			if (isNaN(offset))
				offset = 0;
			var match = $('#' + this.instance.data('heightmatch'));
			if (match.length) {
				match.css('height', h + offset);
			}
		}
	},
	
	// start auto transition
	start: function() {
		var ptr = this;
		clearInterval(this.interval);
		
		if (this.delay)
			this.interval = setInterval(function() { ptr.next() }, this.delay);
	},
	
	// go to the next slide
	next: function() {
		var next = this.current + 1;
		if (next >= this.total)
			next = 0;
	
		this.go(next);
	},
	
	// go to the next slide
	prev: function() {
		var prev = this.current - 1;
		if (prev < 0)
			prev = this.total - 1;
	
		this.go(prev);
	},
	
	// jump to a specific slide
	go: function(slide) {
		this.current = slide;
		this.instance.find('.container').stop().animate({left:(this.current * -100) + '%'}, 500);
		
		// update caption, if it exists
		var cap = $(this.instance).data('caption');
		if (cap != undefined && cap != '') {
			var elCap = $('#' + $(this.instance).data('caption'));
			if (elCap.length)
				elCap.html($($(this.instance).find('.item')[this.current]).data('caption'));
		}
		
		// update nav
		this.updateNav();
		
		// reset the interval timer
		this.start();
	},
	
	// update nav to reflect current slide
	updateNav: function() {
		var ptr = this;
		this.instance.find('.controls li').each(function(index) {
			if (index == ptr.current)
				$(this).addClass('active');
			else
				$(this).removeClass('active');
		});
	}
	
};




// DOM Ready
/* $(function(){ */
window.onload = function() {
/* 	setTimeout(function() { TAB.init() }, 3000); */
	TAB.init();
};
/* 	TAB.init(); */
/* }); */
